import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/game.js';
import {ENEMIES} from '../src/data.js';
import {freshProfile,seeded} from '../src/rules.js';

const nodes=new Map();
globalThis.document={getElementById(id){if(!nodes.has(id))nodes.set(id,{textContent:'',classList:{add(){},remove(){}}});return nodes.get(id);}};
globalThis.window={addEventListener(){}};
function make(){const mem=new Map();globalThis.localStorage={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};const g=new Game({addEventListener(){}});g.start(false);g.ui.close();g.rng=seeded(104);return g;}
function isolated(){const g=make();g.enemies=[];return g;}
function step(g,seconds){for(let t=0;t<seconds;t+=1/60)g.tick(1/60);}

test('a fresh hunt spawns 17 enemies over three halls',()=>{const g=make();assert.equal(g.enemies.length,17);assert.equal(g.enemies.filter(e=>e.kind==='boss').length,1);assert.equal(g.player.hp,150);assert.equal(g.mode,'playing');});
test('WASD input moves at a bounded speed',()=>{const g=isolated();g.input.vector={x:1,z:0};g.updatePlayer(.1);assert.ok(g.player.pos.x>.5&&g.player.pos.x<=.61);});
test('dash consumes stamina, gives invulnerability and enforces cooldown',()=>{const g=make();g.action('dash');assert.equal(g.player.stamina,75);assert.ok(g.player.invuln>.3);const hp=g.player.hp;g.damagePlayer(100);assert.equal(g.player.hp,hp);g.action('dash');assert.equal(g.player.stamina,75);});
test('no-essence cast is rejected without entering cooldown',()=>{const g=make();g.player.mana=0;g.action('rift');assert.equal(g.projectiles.length,0);assert.equal(g.player.cooldowns.rift,0);});
test('three-strike melee deals real damage and advances combo',()=>{const g=isolated();const e=g.spawnEnemy('brute',0,10,0);const start=e.hp;g.action('attack');g.updatePlayer(.17);assert.ok(e.hp<start);g.updatePlayer(.3);g.action('attack');assert.equal(g.player.combo,1);g.updatePlayer(.5);g.action('attack');assert.equal(g.player.combo,2);});
test('melee does not damage a distant enemy',()=>{const g=isolated(),e=g.spawnEnemy('knight',0,-10,0);g.action('attack');g.updatePlayer(.2);assert.equal(e.hp,e.maxHP);});
test('piercing rift hits each enemy once instead of every substep',()=>{const g=isolated();g.rng=()=>.9;const a=g.spawnEnemy('brute',0,8,0),b=g.spawnEnemy('brute',0,5,0);const hp=a.hp;g.action('rift');for(let i=0;i<60;i++)g.updateProjectiles(1/60);const expected=Math.round(g.stat.damage*2.15);assert.equal(hp-a.hp,expected);assert.equal(b.maxHP-b.hp,expected);});
test('kills award XP and crystals exactly once',()=>{const g=isolated(),e=g.spawnEnemy('knight',0,10,0);g.hitEnemy(e,999);const gold=g.profile.gold,xp=g.profile.xp;assert.equal(g.profile.kills,1);assert.equal(xp,ENEMIES.knight.xp);g.hitEnemy(e,999);g.killEnemy(e);assert.equal(g.profile.gold,gold);assert.equal(g.profile.kills,1);});
test('extraction requires a real nearby unclaimed corpse',()=>{const g=isolated();g.action('extract');assert.equal(g.profile.shadows.length,0);const e=g.spawnEnemy('knight',0,10,0);g.hitEnemy(e,999);g.action('extract');assert.deepEqual(g.profile.shadows,['knight']);assert.equal(e.extracted,true);g.player.cooldowns.extract=0;g.action('extract');assert.equal(g.profile.shadows.length,1);});
test('shadow capacity prevents consuming extra corpses',()=>{const g=isolated();g.profile.shadows=['knight','knight','hound'];const e=g.spawnEnemy('mage',0,10,0);g.hitEnemy(e,999);g.action('extract');assert.equal(e.extracted,false);assert.equal(g.profile.shadows.length,3);});
test('summoned shadows attack, expire, and are not made without a roster',()=>{const g=isolated();g.action('army');assert.equal(g.shadows.length,0);g.profile.shadows=['knight'];g.action('army');assert.equal(g.shadows.length,1);const a=g.shadows[0];const e=g.spawnEnemy('brute',a.pos.x,a.pos.z+1,0);g.updateShadows(.3);assert.ok(e.hp<e.maxHP);g.updateShadows(25);assert.equal(g.shadows.length,0);});
test('potions heal exactly up to the health cap',()=>{const g=make();g.player.hp=120;g.action('potion');assert.equal(g.player.hp,150);assert.equal(g.player.potions,2);g.player.cooldowns.potion=0;g.action('potion');assert.equal(g.player.potions,2);});
test('stat spending and equipment changes persist and affect stats',()=>{const g=make();g.profile.points=2;g.spendAttribute('strength');assert.equal(g.stat.damage,26);assert.equal(g.profile.points,1);g.spendAttribute('notAnAttribute');assert.equal(g.profile.points,1);g.profile.inventory.push({slot:'weapon',id:'test',name:'Test',rarity:2,power:20});g.equip(0);assert.equal(g.stat.damage,46);assert.equal(g.profile.inventory[0].id,'starter-blade');});
test('a completed hall offers one boon, opens a gate, and remains cleared on reload',()=>{const g=make();for(const e of g.enemies.filter(e=>e.zone===0))g.hitEnemy(e,99999);g.updateProgress(.1);g.updateProgress(1.1);assert.equal(g.ui.kind,'boon');const id=g.ui.choices[0].id;g.ui.choose(id);assert.ok(g.world.gates[0].open);assert.ok(g.profile.cleared.includes(0));g.start(true);assert.equal(g.enemies.filter(e=>e.zone===0).length,0);g.updateProgress(3);assert.notEqual(g.ui.kind,'boon');assert.deepEqual(g.profile.boons,[id]);});
test('crossing into a new hall records a checkpoint and restores supplies',()=>{const g=make();g.player.hp=20;g.player.potions=0;g.player.pos={x:0,z:-29};g.updateProgress(.01);assert.equal(g.zone,1);assert.equal(g.profile.checkpoint,1);assert.equal(g.player.potions,3);assert.equal(g.player.hp,g.stat.maxHP);});
test('enemy attacks wind up before damaging a hunter',()=>{const g=isolated();g.player.pos={x:0,z:2};const e=g.spawnEnemy('knight',0,0,0);e.active=true;g.updateEnemy(e,.01);assert.equal(e.state,'windup');assert.equal(g.player.hp,150);g.updateEnemy(e,.8);assert.ok(g.player.hp<150);assert.equal(e.state,'recover');});
test('moving outside a telegraphed strike avoids it',()=>{const g=isolated();g.player.pos={x:0,z:2};const e=g.spawnEnemy('knight',0,0,0);g.beginEnemyAttack(e,g.player);g.player.pos.x=8;g.executeEnemyAttack(e);assert.equal(g.player.hp,150);});
test('boss phase changes and attack patterns are active',()=>{const g=isolated();g.zone=2;g.player.pos={x:0,z:-94};const e=g.spawnEnemy('boss',0,-97,2);e.active=true;e.hp=e.maxHP*.5;g.updateEnemy(e,.01);assert.equal(e.phase,2);e.hp=e.maxHP*.2;g.updateEnemy(e,.01);assert.equal(e.phase,3);e.attackIndex=0;g.beginEnemyAttack(e,g.player);assert.equal(e.pattern,'sigils');assert.equal(g.hazards.length,3);});
test('death saves progression, applies penalty once, and retry restores checkpoint',()=>{const g=make();g.profile.gold=100;g.damagePlayer(100000,'Test enemy');assert.equal(g.mode,'dead');assert.equal(g.profile.deaths,1);assert.equal(g.profile.gold,90);g.damagePlayer(100000);assert.equal(g.profile.deaths,1);g.retry();assert.equal(g.mode,'playing');assert.equal(g.profile.deaths,1);assert.equal(g.player.hp,g.stat.maxHP);});
test('the monarch death leads to victory and Ascension retains the hunter',()=>{const g=make();g.zone=2;g.player.pos={x:0,z:-97};const e=g.enemies.find(e=>e.kind==='boss');g.hitEnemy(e,100000);g.updateProgress(3.1);assert.equal(g.mode,'won');assert.equal(g.profile.victories,1);const level=g.profile.level;g.ascend();assert.equal(g.profile.cycle,1);assert.equal(g.profile.level,level);assert.equal(g.profile.boons.length,0);assert.equal(g.profile.cleared.length,0);assert.equal(g.enemies.length,17);});
test('paused hunt freezes movement, projectiles, and resource regeneration',()=>{const g=make();g.action('rift');g.player.mana=10;g.ui.pause();const pos={...g.player.pos},life=g.projectiles[0].life;step(g,1);assert.deepEqual(g.player.pos,pos);assert.equal(g.projectiles[0].life,life);assert.equal(g.player.mana,10);});
test('coffers and lore cannot award repeatedly',()=>{const g=make();g.player.pos={x:-9,z:8};g.updateProgress(.01);assert.equal(g.interaction.kind,'chest');g.interact();assert.equal(g.profile.opened.length,1);const gold=g.profile.gold;g.updateProgress(.01);g.interact();assert.equal(g.profile.gold,gold);});
test('frame simulation runs through repeated encounters without non-finite state',()=>{const g=make();g.store.settings.difficulty='story';for(let i=0;i<600;i++){g.input.attackHeld=true;const e=g.closestEnemy(g.player.pos,100);if(e){const dx=e.pos.x-g.player.pos.x,dz=e.pos.z-g.player.pos.z,n=Math.max(.001,Math.hypot(dx,dz));g.input.vector=n>2?{x:dx/n,z:dz/n}:{x:0,z:0};}g.tick(1/60);if(g.ui.kind==='boon')g.ui.choose(g.ui.choices[0].id);if(g.mode==='dead')break;}assert.ok(Number.isFinite(g.player.hp));assert.ok(Number.isFinite(g.player.pos.x));assert.ok(Number.isFinite(g.player.pos.z));assert.ok(g.profile.kills>0);});
