import * as T from 'three';
import {ring} from './models.js';
import {seeded,clamp} from './rules.js';
export class Effects {
 constructor(scene){this.scene=scene;this.random=seeded(427);this.max=1300;this.parts=Array.from({length:this.max},()=>({life:0}));this.cursor=0;this.items=[];this.temp=new T.Object3D();this.color=new T.Color();
 this.mesh=new T.InstancedMesh(new T.IcosahedronGeometry(1,0),new T.MeshBasicMaterial({color:0xffffff,toneMapped:false}),this.max);this.mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);this.mesh.frustumCulled=false;this.mesh.count=0;scene.add(this.mesh);this.materials=new Map();
 }
 burst(x,y,z,color,count=20,speed=3,size=.065,gravity=3){for(let i=0;i<count;i++){const a=this.random()*Math.PI*2,u=this.random()*2-1,s=speed*(.3+this.random()*.7);const p=this.parts[this.cursor++%this.max];Object.assign(p,{x,y,z,vx:Math.cos(a)*s,vy:Math.abs(u)*s+.2,vz:Math.sin(a)*s,life:.35+this.random()*.6,maxLife:1,size:size*(.4+this.random()),color,gravity});}}
 mist(x,z,color=0x7c79ff,count=5){for(let i=0;i<count;i++){const a=this.random()*Math.PI*2,r=this.random()*.65;const p=this.parts[this.cursor++%this.max];Object.assign(p,{x:x+Math.cos(a)*r,y:.1,z:z+Math.sin(a)*r,vx:0,vy:.65+this.random(),vz:0,life:.5+this.random()*.4,size:.04+this.random()*.025,color,gravity:-.2});}}
 pulse(x,z,color=0x719eff,radius=4,duration=.45){const g=new T.Group();g.position.set(x,.04,z);this.scene.add(g);const r=ring(g,1,color,.01,.027);r.material.opacity=.95;this.items.push({type:'pulse',group:g,mesh:r,life:duration,duration,radius});}
 slash(x,z,angle,combo=0,radius=2.7,color=0x96baff){const g=new T.Group();g.position.set(x,.9,z);g.rotation.y=angle;g.rotation.z=combo===2?.15:(combo%2?.22:-.22);this.scene.add(g);const arc=new T.Mesh(new T.RingGeometry(radius*.72,radius,36,1,-.55,Math.PI*1.18),new T.MeshBasicMaterial({color,transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false,blending:T.AdditiveBlending}));arc.rotation.x=-Math.PI/2;arc.rotation.z=.55-Math.PI*1.09;g.add(arc);const edge=new T.Mesh(new T.RingGeometry(radius*.98,radius*1.02,36,1,-.55,Math.PI*1.18),new T.MeshBasicMaterial({color:0xeaf4ff,transparent:true,opacity:.95,side:T.DoubleSide,depthWrite:false,blending:T.AdditiveBlending}));edge.rotation.copy(arc.rotation);edge.position.y=.012;g.add(edge);this.items.push({type:'slash',group:g,mesh:arc,edge,life:.22,duration:.22});}
 telegraph(x,z,radius,duration,color=0xf36058){const g=new T.Group();g.position.set(x,.044,z);this.scene.add(g);const fill=new T.Mesh(new T.CircleGeometry(radius,64),new T.MeshBasicMaterial({color,transparent:true,opacity:.095,side:T.DoubleSide,depthWrite:false}));fill.rotation.x=-Math.PI/2;g.add(fill);const rim=ring(g,radius,color,.015,.045),progress=ring(g,.99,color,.023,.03);const item={type:'telegraph',group:g,mesh:rim,fill,progress,life:duration,duration,radius};this.items.push(item);return item;}
 projectile(x,y,z,color=0x92a9ff,size=.17){const g=new T.Group();g.position.set(x,y,z);const core=new T.Mesh(new T.IcosahedronGeometry(size,1),new T.MeshBasicMaterial({color}));g.add(core);const halo=new T.Mesh(new T.IcosahedronGeometry(size*1.8,0),new T.MeshBasicMaterial({color,transparent:true,opacity:.15,blending:T.AdditiveBlending,depthWrite:false}));g.add(halo);this.scene.add(g);return g;}
 release(group){group.removeFromParent();group.traverse(o=>{if(o.isMesh){o.geometry.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});}
 tick(dt){let n=0;for(const p of this.parts){if(p.life<=0)continue;p.life-=dt;if(p.life<=0)continue;p.vy-=p.gravity*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;if(p.y<.035){p.y=.035;p.vy=Math.abs(p.vy)*.35;p.vx*=.93;p.vz*=.93;}this.temp.position.set(p.x,p.y,p.z);this.temp.rotation.set(p.x*3,p.life*5,p.z);this.temp.scale.setScalar(p.size*Math.min(1,p.life*4));this.temp.updateMatrix();this.mesh.setMatrixAt(n,this.temp.matrix);this.color.setHex(p.color).multiplyScalar(1.8);this.mesh.setColorAt(n,this.color);n++;}this.mesh.count=n;this.mesh.instanceMatrix.needsUpdate=true;if(this.mesh.instanceColor)this.mesh.instanceColor.needsUpdate=true;
  for(let i=this.items.length-1;i>=0;i--){const e=this.items[i];e.life-=dt;if(e.life<=0){this.release(e.group);this.items.splice(i,1);continue;}const p=1-e.life/e.duration;if(e.type==='pulse'){e.group.scale.setScalar(.2+p*e.radius);e.mesh.material.opacity=(1-p)*.85;}else if(e.type==='slash'){e.mesh.material.opacity=(1-p)*.85;e.edge.material.opacity=(1-p);e.group.rotation.y+=dt*4;e.group.scale.setScalar(.75+p*.4);}else if(e.type==='telegraph'){e.progress.scale.setScalar(Math.max(.001,e.radius*p));e.fill.material.opacity=.06+p*.14;e.mesh.material.opacity=.5+p*.5;}}
 }
 clear(){for(const p of this.parts)p.life=0;for(const e of this.items)this.release(e.group);this.items.length=0;this.mesh.count=0;}
}
