import * as T from 'three';
import {BOONS,stats,nextLevelXP,RARITIES,RARITY_COLORS,clamp} from './rules.js';
import {ZONES,ENEMIES,SKILLS,LORE} from './data.js';
const $=id=>document.getElementById(id);
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function icon(name){const paths={sword:'<path d="M5 27 24 5l3-1-1 4L8 29M4 20l8 7M18 24 4 8 3 4l4 1 20 22M21 20l7 7"/>',dash:'<path d="m3 21 11-6-4-8 16 4-10 8 6 7-13-1M1 28h10M3 4h7"/>',rift:'<path d="m20 2-9 11 9 5-11 12M25 6l-4 7 7 5M9 4 3 15l6 6"/>',hand:'<path d="M8 27 3 18q-1-3 2-2l5 4V9q0-4 3-2v9-12q0-3 3-1v13-9q0-3 3-1v11-6q0-3 3-1v10l-4 7ZM7 3l-2 4M25 3l2 4"/>',crown:'<path d="m4 10 7 6 5-11 5 11 7-6-4 17H8ZM9 30h14M12 22h8"/>',drop:'<path d="M16 3S5 16 5 22a11 9 0 0 0 22 0C27 16 16 3 16 3ZM10 21q0 5 5 5"/>',heart:'<path d="M16 28S3 20 3 11C3 2 14 2 16 9c2-7 13-7 13 2 0 9-13 17-13 17Z"/>',eye:'<path d="M2 16s5-9 14-9 14 9 14 9-5 9-14 9S2 16 2 16Z"/><circle cx="16" cy="16" r="4"/>'};return `<svg viewBox="0 0 32 32" aria-hidden="true">${paths[name]||paths.crown}</svg>`;}
export class UI {
 constructor(game){this.game=game;this.modalOpen=false;this.canClose=true;this.kind='';this.floats=[];this.tags=new Map();this.bannerTime=0;this.updateTime=0;this.mapTime=0;this.notices=[];this.proj=new T.Vector3();
  $('hotbar').innerHTML=Object.entries(SKILLS).map(([id,s])=>`<button class="skill" id="skill-${id}" data-skill="${id}" aria-label="${s.name}: ${s.desc}">${icon(s.icon)}<kbd>${s.key}</kbd><div class="cooldown"></div><span class="cooldown-text"></span><span class="charge"></span><span class="tip"><strong>${s.name}</strong>${s.desc}</span></button>`).join('');
  for(const el of document.querySelectorAll('[data-skill]')){el.addEventListener('pointerdown',e=>{e.stopPropagation();e.preventDefault();game.action(el.dataset.skill);});}
  $('start-btn').onclick=()=>{if(game.store.load())this.confirmNew();else game.start(false);};$('continue-btn').onclick=()=>game.start(true);$('title-settings').onclick=()=>this.settings();$('title-help').onclick=()=>this.help();$('menu-icon').onclick=()=>this.pause();$('modal-close').onclick=()=>this.close();$('touch-inventory').onclick=()=>this.inventory();
  $('modal').addEventListener('pointerdown',e=>{if(e.target===$('modal'))this.close();});
 }
 title(){this.close(true);$('hud').classList.add('hidden');$('title-screen').classList.remove('hidden');const saved=this.game.store.load();$('continue-btn').classList.toggle('hidden',!saved);$('start-btn').innerHTML=saved?'NEW HUNT <span>↗</span>':'ENTER THE GATE <span>↗</span>';$('loading').classList.add('hidden');}
 play(){this.close(true);$('title-screen').classList.add('hidden');$('hud').classList.remove('hidden');this.clearTags();}
 modal(html,kind='menu',canClose=true){this.game.input?.clear();this.modalOpen=true;this.canClose=canClose;this.kind=kind;$('modal-content').innerHTML=html;$('modal').classList.remove('hidden');$('modal-close').classList.toggle('hidden',!canClose);this.game.sound.play('ui');const focus=$('modal-content').querySelector('button,select');if(focus)setTimeout(()=>focus.focus({preventScroll:true}),40);}
 close(force=false){if(!this.canClose&&!force)return;this.modalOpen=false;this.kind='';$('modal').classList.add('hidden');this.game.input?.clear();}
 pause(){if(this.game.mode!=='playing')return;if(this.modalOpen){this.close();return;}this.modal(`<div class="eyebrow">THE SYSTEM / HUNT PAUSED</div><h2>Catch your breath.</h2><p class="subtext">Your hunter record is saved automatically. Returning later restarts the current hall; claimed loot and progression remain yours.</p><div class="modal-actions"><button class="primary" id="resume">RESUME HUNT <span>↗</span></button><button id="pause-record">HUNTER RECORD</button><button id="pause-settings">SETTINGS</button><button id="pause-help">CONTROLS</button><button class="subtle" id="return-title">SAVE & RETURN TO TITLE</button></div>`,'pause');$('resume').onclick=()=>this.close();$('pause-record').onclick=()=>this.inventory();$('pause-settings').onclick=()=>this.settings();$('pause-help').onclick=()=>this.help();$('return-title').onclick=()=>this.game.toTitle();}
 help(){const controls=[['W A S D','Move relative to the camera'],['LMB / J','Hold for a three-strike sword combo'],['SPACE','Dodge · brief invulnerability'],['Q','Rift Cleave · piercing shadow wave'],['E','Extract a nearby fallen enemy'],['R','Arise · summon your shadow army'],['1','Drink a recovery potion'],['F','Open chests, read tablets, use shrine'],['RMB drag','Orbit the camera'],['SCROLL','Adjust camera distance'],['TAB / I','Equipment and character attributes'],['ESC / H','Pause / this controls screen']];this.modal(`<div class="eyebrow">HUNTER’S FIELD MANUAL</div><h2>You do not fight alone.</h2><p class="subtext">Clear three halls and defeat Vael. Hunt, extract, grow stronger. Attacks gently target nearby enemies; concentrate on positioning and timing.</p><div class="control-grid">${controls.map(([k,v])=>`<div class="control-row"><kbd>${k}</kbd><span>${v}</span></div>`).join('')}</div><div class="tip-box"><b>First fight:</b> approach a sentinel, hold left click to attack, and dodge when its red circle fills. A defeated enemy leaves a violet remnant: press E nearby, then R to summon it. Q hits multiple enemies. Spend level-up points in your hunter record.<br><br><b>Touch:</b> left stick to move, drag the world to orbit, hold the sword button to attack. Q, E, R and the cross match their desktop skills. F interacts. Landscape is recommended.</div><div class="modal-actions"><button class="primary" id="help-close">UNDERSTOOD <span>↗</span></button></div>`,'help');$('help-close').onclick=()=>this.close();}
 settings(){const s=this.game.store.settings;this.modal(`<div class="eyebrow">SYSTEM CONFIGURATION</div><h2>Make the hunt yours.</h2><div class="settings-grid"><div class="setting"><label for="quality-setting">GRAPHICS QUALITY</label><select id="quality-setting">${['low','medium','high','ultra'].map(q=>`<option value="${q}" ${q===s.quality?'selected':''}>${q.toUpperCase()}${q==='low'?' · no bloom or shadows':q==='medium'?' · lighter rendering':q==='ultra'?' · 4K shadow map':''}</option>`).join('')}</select></div><div class="setting"><label for="difficulty-setting">DIFFICULTY</label><select id="difficulty-setting">${[['story','STORY · forgiving incoming damage'],['normal','HUNTER · intended balance'],['hard','NIGHTMARE · dangerous incoming damage']].map(([k,v])=>`<option value="${k}" ${k===s.difficulty?'selected':''}>${v}</option>`).join('')}</select></div><div class="setting"><label for="volume-setting">MASTER VOLUME</label><input id="volume-setting" type="range" min="0" max="100" value="${Math.round(s.volume*100)}"></div><div class="setting">${[['music','Atmospheric score'],['shake','Camera shake'],['damageNumbers','Damage numbers'],['showFPS','Performance display']].map(([k,v])=>`<label class="toggle-line">${v}<input type="checkbox" data-setting="${k}" ${s[k]?'checked':''}></label>`).join('')}</div></div><p class="subtext" style="margin-top:22px">Medium is the recommended starting point on phones. Low turns off post-processing and real-time shadows. Difficulty can be changed during a hunt.</p><div class="modal-actions"><button class="primary" id="settings-close">APPLY & RETURN <span>↗</span></button></div>`,'settings');$('quality-setting').onchange=e=>{s.quality=e.target.value;this.game.view.setQuality(s.quality);this.game.store.saveSettings();};$('difficulty-setting').onchange=e=>{s.difficulty=e.target.value;this.game.store.saveSettings();};$('volume-setting').oninput=e=>{s.volume=+e.target.value/100;this.game.sound.update();this.game.store.saveSettings();};for(const e of document.querySelectorAll('[data-setting]'))e.onchange=()=>{s[e.dataset.setting]=e.checked;this.game.sound.update();this.game.store.saveSettings();};$('settings-close').onclick=()=>this.close();}
 inventory(){const p=this.game.profile,s=stats(p);const att=[['strength','Strength','Weapon damage'],['vitality','Vitality','Health and armour'],['agility','Agility','Critical chance and cooldowns'],['spirit','Spirit','Essence and shadow power']];const equipped=Object.values(p.equipment).map(i=>`<div class="equipped"><small>${i.slot.toUpperCase()} / ${RARITIES[i.rarity].toUpperCase()}</small><strong style="color:${RARITY_COLORS[i.rarity]}">${esc(i.name)}</strong><span>+${i.power} ${i.slot==='weapon'?'weapon power':'armour'}</span></div>`).join('');
  this.modal(`<div class="eyebrow">THE SYSTEM / PLAYER RECORD</div><h2>The Unchosen <span style="font:14px Arial;color:#a99bd6">LV ${p.level}</span></h2><p class="subtext">${p.points} unspent attribute point${p.points===1?'':'s'} · ${p.gold} crystals · ${p.kills} enemies defeated</p><div class="inventory-layout"><div><h3>ATTRIBUTES</h3>${att.map(([k,n,d])=>`<div class="stat-row"><span>${n}<small style="display:block;font-size:8px;color:#7288ac;margin-top:4px">${d}</small></span><span class="stat-value"><b>${p.attributes[k]}</b><button data-attribute="${k}" ${p.points<1?'disabled':''} aria-label="Increase ${n}">+</button></span></div>`).join('')}<div class="stat-row"><span>Weapon damage</span><b>${Math.round(s.damage)}</b></div><div class="stat-row"><span>Critical chance</span><b>${Math.round(s.crit*100)}%</b></div><div class="stat-row"><span>Maximum health</span><b>${s.maxHP}</b></div><h3>SHADOW ROSTER ${p.shadows.length}/${s.shadowLimit}</h3><div class="small">${p.shadows.length?p.shadows.map((k,i)=>`<div class="stat-row"><span>${esc(ENEMIES[k].name)}</span><button data-dismiss="${i}" title="Release shadow" aria-label="Release ${esc(ENEMIES[k].name)}">×</button></div>`).join(''):'Extract fallen enemies with E to build your army.'}</div></div><div><h3>EQUIPPED</h3>${equipped}<h3>INVENTORY ${p.inventory.length}/30</h3><div class="item-list">${p.inventory.length?p.inventory.map((i,idx)=>`<div class="inventory-item"><div><strong style="color:${RARITY_COLORS[i.rarity]}">${esc(i.name)}</strong><small>${RARITIES[i.rarity]} · +${i.power} ${i.slot==='weapon'?'power':'armour'} ${i.power>p.equipment[i.slot].power?'↑':''}</small></div><div class="item-actions"><button data-equip="${idx}">EQUIP</button><button data-sell="${idx}" title="Salvage for ${6+i.rarity*7} crystals">◇ ${6+i.rarity*7}</button></div></div>`).join(''):'<p class="empty-note">Open chests and defeat enemies to discover equipment. Better gear is not automatically equipped.</p>'}</div><h3>SHADOW BLESSINGS</h3><p class="small">${p.boons.length?p.boons.map(id=>esc(BOONS.find(b=>b.id===id)?.name||'')).join(' · '):'Clear a hall to choose your first blessing.'}</p></div></div><div class="modal-actions"><button class="primary" id="record-close">RETURN TO HUNT <span>↗</span></button><button id="export-save">EXPORT SAVE</button><button id="import-save">IMPORT SAVE</button><input id="save-file" type="file" accept=".json,application/json" hidden></div>`,'inventory');
  $('record-close').onclick=()=>this.close();for(const el of document.querySelectorAll('[data-attribute]'))el.onclick=()=>{this.game.spendAttribute(el.dataset.attribute);this.inventory();};for(const el of document.querySelectorAll('[data-equip]'))el.onclick=()=>{this.game.equip(+el.dataset.equip);this.inventory();};for(const el of document.querySelectorAll('[data-sell]'))el.onclick=()=>{this.game.sell(+el.dataset.sell);this.inventory();};for(const el of document.querySelectorAll('[data-dismiss]'))el.onclick=()=>{this.game.releaseShadow(+el.dataset.dismiss);this.inventory();};$('export-save').onclick=()=>this.game.store.export(p);$('import-save').onclick=()=>$('save-file').click();$('save-file').onchange=async e=>{try{const imported=await this.game.store.import(e.target.files[0]);this.confirmImport(imported);}catch(error){this.toast(error.message,'danger');}};
 }
 confirmImport(profile){this.modal(`<div class="eyebrow">REPLACE HUNTER RECORD</div><h2>Import level ${profile.level} hunter?</h2><p class="subtext">This replaces the local hunter record and restarts at the imported checkpoint. Export your current save first to keep it.</p><div class="modal-actions"><button class="primary" id="do-import">REPLACE & LOAD</button><button id="cancel-import">CANCEL</button></div>`,'import');$('do-import').onclick=()=>{this.game.store.save(profile);this.game.start(true);};$('cancel-import').onclick=()=>this.inventory();}
 confirmNew(){this.modal(`<div class="eyebrow">A NEW SHADOW</div><h2>Start a new hunter?</h2><p class="subtext">This replaces your local saved hunter. Your current record can be exported from the hunter record during play.</p><div class="modal-actions"><button class="primary" id="new-confirm">START NEW HUNT</button><button id="new-cancel">KEEP MY HUNTER</button></div>`,'confirm');$('new-confirm').onclick=()=>this.game.start(false);$('new-cancel').onclick=()=>this.close();}
 chooseBoon(choices,onChoose){this.modal(`<div class="eyebrow">HALL CLEARED / REWARD AVAILABLE</div><h2>Power always has a price.</h2><p class="subtext">Choose one blessing. It lasts for this descent. Your next checkpoint will restore health, essence and potions.</p><div class="upgrade-cards">${choices.map(b=>`<button class="upgrade-card" data-boon="${b.id}">${icon(b.icon)}<span class="eyebrow">${b.tag}</span><h4>${b.name}</h4><p>${b.desc}</p></button>`).join('')}</div>`,'boon',false);for(const el of document.querySelectorAll('[data-boon]'))el.onclick=()=>{this.close(true);onChoose(el.dataset.boon);};}
 shrine(){const p=this.game.profile,price=35+Math.floor(p.equipment.weapon.power*1.2);this.modal(`<div class="eyebrow">SHRINE OF THE UNCHOSEN</div><h2>A moment outside death.</h2><p class="subtext">The crystal responds to your presence. Spend the fragments carried by the fallen to strengthen your blades or replenish your supplies.</p><h3>${p.gold} CRYSTALS AVAILABLE</h3><div class="upgrade-cards" style="grid-template-columns:1fr 1fr"><button class="upgrade-card" id="forge" ${p.gold<price?'disabled':''}>${icon('sword')}<span class="eyebrow">${price} CRYSTALS</span><h4>Temper the edge</h4><p>Permanently add 5 weapon power to your equipped weapon.</p></button><button class="upgrade-card" id="restore" ${p.gold<20?'disabled':''}>${icon('drop')}<span class="eyebrow">20 CRYSTALS</span><h4>Restore the hunter</h4><p>Restore all health, essence and your three recovery potions.</p></button></div><div class="modal-actions"><button id="shrine-record">HUNTER RECORD</button><button id="shrine-close">LEAVE SHRINE</button></div>`,'shrine');$('forge').onclick=()=>{if(p.gold<price)return;p.gold-=price;p.equipment.weapon.power+=5;this.game.refreshStats();this.game.save();this.game.sound.play('loot');this.shrine();};$('restore').onclick=()=>{if(p.gold<20)return;p.gold-=20;this.game.restore();this.game.save();this.close();this.toast('The shrine restores you.','purple');};$('shrine-close').onclick=()=>this.close();$('shrine-record').onclick=()=>this.inventory();}
 lore(id){const l=LORE[id];this.modal(`<div class="eyebrow">A MEMORY LEFT BEHIND / ${String(id+1).padStart(2,'0')}</div><h2>${l.title}</h2><p class="lore-text">“${l.text}”</p><div class="modal-actions"><button class="primary" id="lore-close">REMEMBER <span>↗</span></button></div>`,'lore');$('lore-close').onclick=()=>this.close();}
 death(){this.modal(`<div class="eyebrow" style="color:#cf90a5">VITAL SIGNAL LOST</div><h2>Not your ending.</h2><p class="subtext">The System pulls you from the dark. Your levels, equipment and shadow roster remain. A small portion of your crystals was lost.</p><div class="tip-box">${this.game.lastDeathTip||'Watch the red ground markers. Dodge as they fill, then punish the recovery. Rift Cleave can hit an entire group, and your shadows can draw enemies away.'}</div><div class="modal-actions"><button class="primary" id="retry">RETURN TO CHECKPOINT <span>↗</span></button><button id="death-settings">CHANGE DIFFICULTY</button><button id="death-title">RETURN TO TITLE</button></div>`,'death',false);$('retry').onclick=()=>this.game.retry();$('death-settings').onclick=()=>{this.settings();this.canClose=false;$('modal-close').classList.add('hidden');$('settings-close').onclick=()=>this.death();};$('death-title').onclick=()=>this.game.toTitle();}
 victory(){const p=this.game.profile;this.modal(`<div class="eyebrow" style="color:#d4b883">GATE CLEARED / MONARCH DEFEATED</div><h2>The shadows know your name.</h2><p class="subtext">Vael’s crown falls silent. For the first time, the gate does not ask what you are. It asks where you will go next.</p><div class="result-stats">${[[p.level,'HUNTER LEVEL'],[p.kills,'ENEMIES DEFEATED'],[p.bestCombo,'BEST HIT CHAIN'],[p.shadows.length,'BOUND SHADOWS']].map(([v,n])=>`<div class="result-stat"><strong>${v}</strong><span>${n}</span></div>`).join('')}</div><div class="tip-box"><b>Ascension ${p.cycle+1} is available.</b> Keep your levels, equipment and shadows. The gate resets, enemies grow stronger, and new loot awaits. Your previous run’s blessings are replaced.</div><div class="modal-actions"><button class="primary" id="ascend">ENTER ASCENSION ${p.cycle+1} <span>↗</span></button><button id="victory-export">EXPORT HUNTER</button><button id="victory-title">RETURN TO TITLE</button></div>`,'victory',false);$('ascend').onclick=()=>this.game.ascend();$('victory-export').onclick=()=>this.game.store.export(p);$('victory-title').onclick=()=>this.game.toTitle();}
 toast(text,type='',duration=3.8){const el=document.createElement('div');el.className='toast '+type;el.textContent=text;$('toasts').appendChild(el);this.notices.push({el,time:duration});if(this.notices.length>4){const old=this.notices.shift();old.el.remove();}}
 banner(small,title,text='',duration=3){$('banner-small').textContent=small;$('banner-title').textContent=title;$('banner-text').textContent=text;$('center-banner').classList.remove('hidden');this.bannerTime=duration;}
 number(x,y,z,value,type=''){if(!this.game.store.settings.damageNumbers)return;const el=document.createElement('div');el.className='damage-number '+type;el.textContent=value;$('floating').appendChild(el);this.floats.push({el,x,y,z,life:1.0,max:1.0,drift:(this.game.rng()-.5)*.8});if(this.floats.length>65){this.floats.shift().el.remove();}}
 clearTags(){for(const e of this.tags.values())e.remove();this.tags.clear();for(const f of this.floats)f.el.remove();this.floats=[];for(const n of this.notices)n.el.remove();this.notices=[];}
 project(x,y,z){this.proj.set(x,y,z).project(this.game.view.camera);return {x:(this.proj.x*.5+.5)*innerWidth,y:(-.5*this.proj.y+.5)*innerHeight,visible:this.proj.z<1&&this.proj.z>-1&&Math.abs(this.proj.x)<1.2&&Math.abs(this.proj.y)<1.2};}
 tick(dt){
  for(let i=this.floats.length-1;i>=0;i--){const f=this.floats[i];f.life-=dt;if(f.life<=0){f.el.remove();this.floats.splice(i,1);continue;}f.y+=dt*.75;f.x+=dt*f.drift;const p=this.project(f.x,f.y,f.z);f.el.style.left=p.x+'px';f.el.style.top=p.y+'px';f.el.style.opacity=String(p.visible?Math.min(1,f.life*2):0);}
  for(let i=this.notices.length-1;i>=0;i--){const n=this.notices[i];n.time-=dt;if(n.time<=0){n.el.remove();this.notices.splice(i,1);}else n.el.style.opacity=String(Math.min(1,n.time*2));}
  if(this.bannerTime>0){this.bannerTime-=dt;if(this.bannerTime<=0)$('center-banner').classList.add('hidden');}
  this.updateTime-=dt;this.mapTime-=dt;if(this.game.mode!=='playing'&&this.game.mode!=='dead'&&this.game.mode!=='won')return;
  if(this.updateTime>0)return;this.updateTime=.065;const g=this.game,p=g.player,s=g.stat,profile=g.profile;
  $('level').textContent=profile.level;$('hp-bar').style.width=clamp(p.hp/s.maxHP*100,0,100)+'%';$('hp-label').textContent=`${Math.ceil(p.hp)} / ${s.maxHP}`;$('mana-bar').style.width=clamp(p.mana/s.maxMana*100,0,100)+'%';$('mana-label').textContent=`${Math.floor(p.mana)} / ${s.maxMana}`;$('stamina-bar').style.width=clamp(p.stamina,0,100)+'%';$('xp-bar').style.width=clamp(profile.xp/nextLevelXP(profile.level)*100,0,100)+'%';$('coins').textContent=profile.gold;
  const zone=ZONES[g.zone];$('location-name').textContent=zone.name;$('location-rank').textContent=`${zone.rank}-RANK GATE / 0${g.zone+1}`;$('rank').textContent=`${profile.level<3?'E':profile.level<5?'D':profile.level<8?'C':'B'}-RANK`;$('cycle-label').textContent=profile.cycle?`ASCENSION ${profile.cycle}`:'';
  const remaining=g.enemies.filter(e=>e.zone===g.zone&&!e.dead).length,cleared=g.cleared.has(g.zone);
  $('quest-title').textContent=g.zone===2?'The hollow crown':g.zone===1?'A choir without voices':'A second awakening';$('quest-text').textContent=cleared?(g.zone===2?'The gate is yours.':'Proceed through the unsealed gate.'):g.zone===2?'Defeat Vael and claim your awakening.':'Defeat the guardians to break the seal.';$('quest-progress').textContent=cleared?'◇ HALL CLEARED':`${remaining} HOSTILE${remaining===1?'':'S'} REMAINING`;
  for(const [id,sk]of Object.entries(SKILLS)){const e=$('skill-'+id);const cd=id==='attack'?p.attackTimer:p.cooldowns[id]||0,max=sk.cooldown*g.stat.cooldown;e.querySelector('.cooldown').style.transform=`scaleY(${clamp(cd/max,0,1)})`;e.querySelector('.cooldown-text').textContent=cd>.3?Math.ceil(cd):'';e.querySelector('.charge').textContent=id==='potion'?p.potions:id==='army'?profile.shadows.length:'';e.classList.toggle('unavailable',(id==='army'&&!profile.shadows.length)||(id==='potion'&&p.potions<=0)||(id!=='dash'&&sk.cost>p.mana));}
  const shadowHTML=Array.from({length:s.shadowLimit},(_,i)=>`<span class="shadow-slot ${profile.shadows[i]?'':'empty'} ${g.shadows[i]&&!g.shadows[i].dead?'active':''}">${profile.shadows[i]?'♟':'·'}</span>`).join('');if($('shadow-slots').innerHTML!==shadowHTML)$('shadow-slots').innerHTML=shadowHTML;$('shadow-status').textContent=g.armyTime>0?`LEGION ACTIVE · ${Math.ceil(g.armyTime)}s`:profile.shadows.length?'R · Arise your legion':'E · Extract the fallen';
  const boss=g.enemies.find(e=>e.kind==='boss'&&!e.dead&&e.active);$('boss-ui').classList.toggle('hidden',!boss||g.zone!==2);if(boss){$('boss-hp').style.width=clamp(boss.hp/boss.maxHP*100,0,100)+'%';$('boss-phase').textContent=['THE FIRST OATH','THE CROWN AWAKENS','NO MORE MERCY'][boss.phase-1];}
  $('combo-ui').classList.toggle('hidden',p.hitChain<3||p.chainTime<=0);$('combo-count').textContent=p.hitChain;
  $('interaction').classList.toggle('hidden',!g.interaction||this.modalOpen);if(g.interaction)$('interaction-label').textContent=g.interaction.label;
  for(const enemy of g.enemies){let tag=this.tags.get(enemy.id);const show=!enemy.dead&&enemy.active&&enemy.kind!=='boss'&&enemy.hp<enemy.maxHP&&Math.hypot(enemy.pos.x-p.pos.x,enemy.pos.z-p.pos.z)<20;if(!show){if(tag)tag.style.display='none';continue;}if(!tag){tag=document.createElement('div');tag.className='enemy-tag';tag.innerHTML='<i></i>';$('floating').appendChild(tag);this.tags.set(enemy.id,tag);}const point=this.project(enemy.pos.x,enemy.height+.55,enemy.pos.z);tag.style.cssText=`position:absolute;width:45px;height:4px;background:#080e1bbb;border:1px solid #e897a74d;transform:translate(-50%,-50%);left:${point.x}px;top:${point.y}px;display:${point.visible?'block':'none'}`;tag.firstChild.style.cssText=`display:block;height:100%;width:${enemy.hp/enemy.maxHP*100}%;background:#d38694`;}
  $('fps').classList.toggle('hidden',!g.store.settings.showFPS);$('fps').textContent=`${g.fps} FPS · ${g.view.renderer.info.render.calls} draws · ${Math.round(g.view.renderer.info.render.triangles/1000)}k tris`;
  if(this.mapTime<=0){this.mapTime=.1;this.drawMap();}
 }
 drawMap(){const c=$('minimap'),ctx=c.getContext('2d'),g=this.game,p=g.player.pos,s=3;ctx.clearRect(0,0,180,180);ctx.fillStyle='#0a1320';ctx.fillRect(0,0,180,180);ctx.save();ctx.translate(90-p.x*s,90-p.z*s);ctx.fillStyle='#1d2b40';ctx.strokeStyle='#587396';ctx.lineWidth=.8;for(const z of ZONES){ctx.fillRect(z.x0*s,z.z0*s,(z.x1-z.x0)*s,(z.z1-z.z0)*s);ctx.strokeRect(z.x0*s,z.z0*s,(z.x1-z.x0)*s,(z.z1-z.z0)*s);}for(const z of [-22,-66])ctx.fillRect(-4.8*s,(z-7)*s,9.6*s,14*s);for(const gate of g.world.gates){ctx.strokeStyle=gate.open?'#708cca':'#c789b2';ctx.lineWidth=gate.open?1:2;ctx.beginPath();ctx.moveTo(-4.5*s,gate.z*s);ctx.lineTo(4.5*s,gate.z*s);ctx.stroke();}for(const chest of g.world.chests){if(!chest.open){ctx.fillStyle='#e8c583';ctx.fillRect(chest.x*s-1.5,chest.z*s-1.5,3,3);}}for(const e of g.enemies){if(!e.dead){ctx.fillStyle=e.kind==='boss'?'#f0879d':'#c98294';ctx.beginPath();ctx.arc(e.pos.x*s,e.pos.z*s,e.kind==='boss'?3:1.7,0,Math.PI*2);ctx.fill();}}for(const a of g.shadows){if(!a.dead){ctx.fillStyle='#b2a0ef';ctx.fillRect(a.pos.x*s-1.5,a.pos.z*s-1.5,3,3);}}ctx.restore();ctx.save();ctx.translate(90,90);ctx.rotate(Math.PI-g.player.angle);ctx.fillStyle='#e3ecff';ctx.beginPath();ctx.moveTo(0,-5);ctx.lineTo(3.5,4);ctx.lineTo(0,2);ctx.lineTo(-3.5,4);ctx.closePath();ctx.fill();ctx.restore();ctx.font='8px Arial';ctx.fillStyle='#8b9db8';ctx.textAlign='center';ctx.fillText('N',90,11);}
}
